import os
import time
import requests
import pandas as pd
import yfinance as yf


# ============================================================
# US500 MACRO INTELLIGENCE
# CORPORATE EARNINGS INTELLIGENCE V3
# S&P 500 MARKET REACTION
# ============================================================
#
# Research-only.
#
# IMPORTANT:
# - No trade execution
# - No Decision Engine integration
# - No Technical Engine modification
# - No market forecast
# - No deterministic prediction
#
# V3 objective:
#
#   Earnings Event
#          ↓
#   Reported Date
#          ↓
#   S&P 500 subsequent reaction
#
# Conservative timing rule:
#
# We DO NOT assume the exact earnings announcement time.
#
# Therefore:
#
#   Event Date = reported_date
#
#   Reaction Day 1 = first trading day AFTER reported_date
#
# This avoids incorrectly treating the event-day close as a
# post-announcement reaction when the earnings release may
# have occurred after market close.
#
# ============================================================


# ============================================================
# CONFIGURATION
# ============================================================

MARKET_TICKER = "^GSPC"

REQUEST_DELAY = float(
    os.getenv(
        "ALPHAVANTAGE_REQUEST_DELAY",
        "1.5"
    )
)

MARKET_START_BUFFER_DAYS = 10

# Trading-day horizons.
#
# These are intentionally defined as trading-session offsets,
# not calendar-day offsets.

HORIZONS = {
    "1d": 1,
    "3d": 3,
    "5d": 5,
    "20d": 20,
    "1m": 21,
    "3m": 63,
}


# ============================================================
# TEST UNIVERSE
# ============================================================

UNIVERSE = [
    {
        "ticker": "MSFT",
        "sector": "Information Technology",
    },
    {
        "ticker": "AAPL",
        "sector": "Information Technology",
    },
    {
        "ticker": "NVDA",
        "sector": "Information Technology",
    },
    {
        "ticker": "AMZN",
        "sector": "Consumer Discretionary",
    },
    {
        "ticker": "WMT",
        "sector": "Consumer Staples",
    },
    {
        "ticker": "JPM",
        "sector": "Financials",
    },
    {
        "ticker": "JNJ",
        "sector": "Health Care",
    },
    {
        "ticker": "XOM",
        "sector": "Energy",
    },
    {
        "ticker": "CAT",
        "sector": "Industrials",
    },
    {
        "ticker": "PG",
        "sector": "Consumer Staples",
    },
]


# ============================================================
# HELPERS
# ============================================================

def to_float(value):
    if value is None:
        return None

    try:
        if isinstance(value, str):
            value = value.strip()

        if value == "":
            return None

        return float(value)

    except (TypeError, ValueError):
        return None


def calculate_pct_change(
    start_price,
    end_price
):
    """
    Percentage change from event reference close
    to future trading-session close.
    """

    if start_price is None:
        return None

    if end_price is None:
        return None

    if start_price == 0:
        return None

    return (
        (end_price - start_price)
        / start_price
        * 100.0
    )


def classify_reaction(
    reaction_pct
):
    """
    Descriptive classification only.

    NOT a trading signal.
    """

    if reaction_pct is None:
        return "UNKNOWN"

    if reaction_pct >= 2.0:
        return "STRONG_POSITIVE"

    if reaction_pct > 0.25:
        return "POSITIVE"

    if reaction_pct >= -0.25:
        return "NEUTRAL"

    if reaction_pct > -2.0:
        return "NEGATIVE"

    return "STRONG_NEGATIVE"


# ============================================================
# LOAD EARNINGS DATA FROM V2
# ============================================================

def load_earnings_data():
    """
    Load the event dataset generated by V2.
    """

    filename = (
        "earnings_breadth_events_v2.csv"
    )

    if not os.path.exists(filename):

        raise FileNotFoundError(
            f"{filename} was not found. "
            "Run Earnings Breadth V2 first."
        )

    df = pd.read_csv(
        filename
    )

    required_columns = [
        "ticker",
        "sector",
        "fiscal_date_ending",
        "reported_date",
        "eps_actual",
        "eps_consensus",
        "eps_surprise",
        "eps_surprise_pct",
        "eps_result_class",
        "point_in_time_safe",
        "historical_analog_eligible",
    ]

    missing = [
        col
        for col in required_columns
        if col not in df.columns
    ]

    if missing:

        raise RuntimeError(
            "Missing required columns: "
            + ", ".join(missing)
        )

    df[
        "reported_date"
    ] = pd.to_datetime(
        df["reported_date"],
        errors="coerce"
    )

    df = df[
        df["reported_date"].notna()
    ].copy()

    return df


# ============================================================
# DOWNLOAD S&P 500 DATA
# ============================================================

def download_market_data(
    earnings_df
):
    """
    Download S&P 500 daily OHLC data once.

    We use the broad index ^GSPC.

    auto_adjust=False is used so the raw index OHLC structure
    is retained.
    """

    min_date = (
        earnings_df[
            "reported_date"
        ].min()
    )

    max_date = (
        earnings_df[
            "reported_date"
        ].max()
    )

    if pd.isna(min_date):
        raise RuntimeError(
            "No valid earnings dates found."
        )

    if pd.isna(max_date):
        raise RuntimeError(
            "No valid earnings dates found."
        )

    start_date = (
        min_date
        - pd.Timedelta(
            days=MARKET_START_BUFFER_DAYS
        )
    )

    # Extra future buffer so that the latest events
    # can reach the required horizons.
    end_date = (
        max_date
        + pd.Timedelta(
            days=150
        )
    )

    print(
        "\n" + "=" * 70
    )

    print(
        "DOWNLOADING S&P 500 MARKET DATA"
    )

    print(
        f"Ticker: {MARKET_TICKER}"
    )

    print(
        f"Start: {start_date.date()}"
    )

    print(
        f"End:   {end_date.date()}"
    )

    print(
        "=" * 70
    )

    market = yf.download(
        MARKET_TICKER,
        start=start_date.strftime(
            "%Y-%m-%d"
        ),
        end=(
            end_date
            + pd.Timedelta(days=1)
        ).strftime(
            "%Y-%m-%d"
        ),
        interval="1d",
        auto_adjust=False,
        progress=False,
        threads=False,
    )

    if market.empty:

        raise RuntimeError(
            "No S&P 500 market data returned."
        )

    # yfinance may return MultiIndex columns.
    if isinstance(
        market.columns,
        pd.MultiIndex
    ):

        market.columns = [
            col[0]
            if isinstance(col, tuple)
            else col
            for col in market.columns
        ]

    market = market[
        [
            "Open",
            "High",
            "Low",
            "Close",
        ]
    ].copy()

    market.index = pd.to_datetime(
        market.index
    )

    market.index = (
        market.index.tz_localize(
            None
        )
        if market.index.tz is not None
        else market.index
    )

    market = (
        market.sort_index()
        .dropna(
            subset=["Close"]
        )
    )

    print(
        f"\nTrading sessions downloaded: "
        f"{len(market)}"
    )

    return market


# ============================================================
# FIND FIRST TRADING SESSION AFTER EVENT
# ============================================================

def get_future_session_positions(
    market_index,
    event_date
):
    """
    Return the integer position of the first trading
    session AFTER the reported earnings date.

    We deliberately exclude the event date itself.
    """

    event_date = pd.Timestamp(
        event_date
    )

    positions = (
        market_index
        > event_date
    )

    matching_positions = (
        positions.nonzero()[0]
    )

    if len(
        matching_positions
    ) == 0:

        return None

    return int(
        matching_positions[0]
    )


# ============================================================
# CALCULATE MARKET REACTION
# ============================================================

def calculate_market_reaction(
    market,
    event_date
):
    """
    Calculate future S&P 500 reactions.

    Reference price:
        CLOSE of the reported-date trading session
        when available.

    Future reaction:
        CLOSE of first trading session after event date,
        then +3, +5, +20, +21, +63 trading sessions.

    IMPORTANT:
    We do not use the same event-day close as +1D.
    """

    market_index = (
        market.index
    )

    event_date = pd.Timestamp(
        event_date
    )

    # --------------------------------------------------------
    # Reference close
    #
    # If the reported date is a weekend/holiday, use the
    # most recent trading session BEFORE the reported date.
    # --------------------------------------------------------

    prior_positions = (
        market_index
        <= event_date
    )

    prior_indices = (
        prior_positions.nonzero()[0]
    )

    if len(
        prior_indices
    ) == 0:

        return None

    event_position = int(
        prior_indices[-1]
    )

    event_market_date = (
        market_index[
            event_position
        ]
    )

    event_close = to_float(
        market.iloc[
            event_position
        ]["Close"]
    )

    if event_close is None:

        return None

    # --------------------------------------------------------
    # First session AFTER reported date
    # --------------------------------------------------------

    first_future_position = (
        get_future_session_positions(
            market_index,
            event_date
        )
    )

    if first_future_position is None:

        return None

    result = {

        "market_event_reference_date":
            event_market_date.strftime(
                "%Y-%m-%d"
            ),

        "market_event_reference_close":
            event_close,

    }

    # --------------------------------------------------------
    # Future horizons
    # --------------------------------------------------------

    for label, offset in (
        HORIZONS.items()
    ):

        future_position = (
            first_future_position
            + offset
            - 1
        )

        if (
            future_position
            >= len(market)
        ):

            result[
                f"sp500_reaction_{label}"
            ] = None

            result[
                f"sp500_close_{label}"
            ] = None

            result[
                f"sp500_reaction_class_{label}"
            ] = "UNAVAILABLE"

            continue

        future_date = (
            market_index[
                future_position
            ]
        )

        future_close = to_float(
            market.iloc[
                future_position
            ]["Close"]
        )

        reaction = (
            calculate_pct_change(
                event_close,
                future_close
            )
        )

        result[
            f"sp500_date_{label}"
        ] = future_date.strftime(
            "%Y-%m-%d"
        )

        result[
            f"sp500_close_{label}"
        ] = future_close

        result[
            f"sp500_reaction_{label}"
        ] = reaction

        result[
            f"sp500_reaction_class_{label}"
        ] = classify_reaction(
            reaction
        )

    # ========================================================
    # 20-SESSION MFE / MAE
    # ========================================================
    #
    # From first trading session after event date through
    # the first 20 trading sessions.
    #
    # MFE:
    # maximum favorable upward excursion.
    #
    # MAE:
    # maximum adverse downward excursion.
    #
    # These are descriptive historical statistics.
    # ========================================================

    window_start = (
        first_future_position
    )

    window_end = min(
        first_future_position + 20,
        len(market)
    )

    future_window = market.iloc[
        window_start:window_end
    ]

    if not future_window.empty:

        highs = (
            pd.to_numeric(
                future_window[
                    "High"
                ],
                errors="coerce"
            )
            .dropna()
        )

        lows = (
            pd.to_numeric(
                future_window[
                    "Low"
                ],
                errors="coerce"
            )
            .dropna()
        )

        if not highs.empty:

            result[
                "sp500_mfe_20d"
            ] = (
                (
                    highs.max()
                    - event_close
                )
                / event_close
                * 100.0
            )

        else:

            result[
                "sp500_mfe_20d"
            ] = None

        if not lows.empty:

            result[
                "sp500_mae_20d"
            ] = (
                (
                    lows.min()
                    - event_close
                )
                / event_close
                * 100.0
            )

        else:

            result[
                "sp500_mae_20d"
            ] = None

    else:

        result[
            "sp500_mfe_20d"
        ] = None

        result[
            "sp500_mae_20d"
        ] = None

    return result


# ============================================================
# BUILD EVENT-REACTION DATASET
# ============================================================

def build_reaction_dataset(
    earnings_df,
    market
):

    rows = []

    total = len(
        earnings_df
    )

    print(
        "\n" + "=" * 70
    )

    print(
        "CALCULATING EARNINGS → S&P 500 REACTIONS"
    )

    print(
        f"Events: {total}"
    )

    print(
        "=" * 70
    )

    for index, (_, row) in enumerate(
        earnings_df.iterrows(),
        start=1
    ):

        ticker = row[
            "ticker"
        ]

        event_date = row[
            "reported_date"
        ]

        print(
            f"[{index}/{total}] "
            f"{ticker} "
            f"{event_date.date()}"
        )

        reaction = (
            calculate_market_reaction(
                market,
                event_date
            )
        )

        output = row.to_dict()

        if reaction is None:

            output[
                "market_reaction_available"
            ] = False

            output[
                "market_reaction_reason"
            ] = (
                "Insufficient S&P 500 data."
            )

        else:

            output.update(
                reaction
            )

            output[
                "market_reaction_available"
            ] = True

            output[
                "market_reaction_reason"
            ] = (
                "Measured from the event-date "
                "reference close to subsequent "
                "trading-session closes."
            )

        # ----------------------------------------------------
        # Point-in-Time safety
        # ----------------------------------------------------

        output[
            "market_reaction_point_in_time_safe"
        ] = True

        output[
            "historical_reaction_eligible"
        ] = (
            bool(
                row[
                    "historical_analog_eligible"
                ]
            )
        )

        rows.append(
            output
        )

    return pd.DataFrame(
        rows
    )


# ============================================================
# REACTION SUMMARY
# ============================================================

def summarize_reactions(
    reaction_df
):

    if reaction_df.empty:

        return pd.DataFrame()

    rows = []

    horizons = [
        "1d",
        "3d",
        "5d",
        "20d",
        "1m",
        "3m",
    ]

    for horizon in horizons:

        column = (
            f"sp500_reaction_{horizon}"
        )

        if column not in reaction_df:
            continue

        values = (
            pd.to_numeric(
                reaction_df[column],
                errors="coerce"
            )
            .dropna()
        )

        if values.empty:
            continue

        rows.append({

            "horizon":
                horizon,

            "observations":
                int(len(values)),

            "mean_pct":
                float(values.mean()),

            "median_pct":
                float(values.median()),

            "p25_pct":
                float(
                    values.quantile(
                        0.25
                    )
                ),

            "p75_pct":
                float(
                    values.quantile(
                        0.75
                    )
                ),

            "minimum_pct":
                float(values.min()),

            "maximum_pct":
                float(values.max()),

            "positive_reaction_pct":
                float(
                    (
                        values > 0
                    ).mean()
                    * 100.0
                ),

            "negative_reaction_pct":
                float(
                    (
                        values < 0
                    ).mean()
                    * 100.0
                ),

        })

    return pd.DataFrame(
        rows
    )


# ============================================================
# REACTION BY EPS RESULT
# ============================================================

def summarize_by_eps_class(
    reaction_df
):

    if reaction_df.empty:

        return pd.DataFrame()

    rows = []

    horizon = "5d"

    column = (
        f"sp500_reaction_{horizon}"
    )

    if column not in reaction_df:

        return pd.DataFrame()

    for result_class, group in (
        reaction_df.groupby(
            "eps_result_class"
        )
    ):

        values = (
            pd.to_numeric(
                group[column],
                errors="coerce"
            )
            .dropna()
        )

        if values.empty:
            continue

        rows.append({

            "eps_result_class":
                result_class,

            "events":
                int(len(values)),

            "mean_sp500_reaction_5d_pct":
                float(values.mean()),

            "median_sp500_reaction_5d_pct":
                float(values.median()),

            "p25_sp500_reaction_5d_pct":
                float(
                    values.quantile(
                        0.25
                    )
                ),

            "p75_sp500_reaction_5d_pct":
                float(
                    values.quantile(
                        0.75
                    )
                ),

            "positive_reaction_pct":
                float(
                    (
                        values > 0
                    ).mean()
                    * 100.0
                ),

            "negative_reaction_pct":
                float(
                    (
                        values < 0
                    ).mean()
                    * 100.0
                ),

        })

    return pd.DataFrame(
        rows
    )


# ============================================================
# REACTION BY SECTOR
# ============================================================

def summarize_by_sector(
    reaction_df
):

    if reaction_df.empty:

        return pd.DataFrame()

    rows = []

    column = (
        "sp500_reaction_5d"
    )

    if column not in reaction_df:

        return pd.DataFrame()

    for sector, group in (
        reaction_df.groupby(
            "sector"
        )
    ):

        values = (
            pd.to_numeric(
                group[column],
                errors="coerce"
            )
            .dropna()
        )

        if values.empty:
            continue

        rows.append({

            "sector":
                sector,

            "events":
                int(len(values)),

            "mean_sp500_reaction_5d_pct":
                float(values.mean()),

            "median_sp500_reaction_5d_pct":
                float(values.median()),

            "p25_sp500_reaction_5d_pct":
                float(
                    values.quantile(
                        0.25
                    )
                ),

            "p75_sp500_reaction_5d_pct":
                float(
                    values.quantile(
                        0.75
                    )
                ),

        })

    return pd.DataFrame(
        rows
    )


# ============================================================
# MAIN
# ============================================================

def main():

    print(
        "\n" + "#" * 70
    )

    print(
        "US500 MACRO INTELLIGENCE"
    )

    print(
        "CORPORATE EARNINGS INTELLIGENCE V3"
    )

    print(
        "S&P 500 MARKET REACTION"
    )

    print(
        "#" * 70
    )

    # --------------------------------------------------------
    # Load V2 events
    # --------------------------------------------------------

    earnings_df = (
        load_earnings_data()
    )

    print(
        f"\nEarnings events loaded: "
        f"{len(earnings_df)}"
    )

    # --------------------------------------------------------
    # Download market
    # --------------------------------------------------------

    market = (
        download_market_data(
            earnings_df
        )
    )

    # --------------------------------------------------------
    # Build reactions
    # --------------------------------------------------------

    reaction_df = (
        build_reaction_dataset(
            earnings_df,
            market
        )
    )

    # --------------------------------------------------------
    # Export event-level dataset
    # --------------------------------------------------------

    reaction_df.to_csv(
        "earnings_market_reaction_v3.csv",
        index=False
    )

    # --------------------------------------------------------
    # Overall summary
    # --------------------------------------------------------

    summary_df = (
        summarize_reactions(
            reaction_df
        )
    )

    summary_df.to_csv(
        "earnings_market_reaction_summary_v3.csv",
        index=False
    )

    # --------------------------------------------------------
    # EPS class summary
    # --------------------------------------------------------

    eps_class_df = (
        summarize_by_eps_class(
            reaction_df
        )
    )

    eps_class_df.to_csv(
        "earnings_reaction_by_eps_class_v3.csv",
        index=False
    )

    # --------------------------------------------------------
    # Sector summary
    # --------------------------------------------------------

    sector_df = (
        summarize_by_sector(
            reaction_df
        )
    )

    sector_df.to_csv(
        "earnings_reaction_by_sector_v3.csv",
        index=False
    )

    # ========================================================
    # OUTPUT
    # ========================================================

    print(
        "\n" + "=" * 70
    )

    print(
        "MARKET REACTION SUMMARY"
    )

    print(
        "=" * 70
    )

    if summary_df.empty:

        print(
            "No reaction summary available."
        )

    else:

        print(
            summary_df.to_string(
                index=False
            )
        )

    print(
        "\n" + "=" * 70
    )

    print(
        "REACTION BY EPS RESULT CLASS"
    )

    print(
        "=" * 70
    )

    if eps_class_df.empty:

        print(
            "No EPS-class reaction summary available."
        )

    else:

        print(
            eps_class_df.to_string(
                index=False
            )
        )

    print(
        "\n" + "=" * 70
    )

    print(
        "REACTION BY SECTOR"
    )

    print(
        "=" * 70
    )

    if sector_df.empty:

        print(
            "No sector reaction summary available."
        )

    else:

        print(
            sector_df.to_string(
                index=False
            )
        )

    # --------------------------------------------------------
    # Coverage
    # --------------------------------------------------------

    available = int(
        reaction_df[
            "market_reaction_available"
        ].sum()
    )

    print(
        "\n" + "=" * 70
    )

    print(
        "V3 COVERAGE"
    )

    print(
        "=" * 70
    )

    print(
        f"Total earnings events: "
        f"{len(reaction_df)}"
    )

    print(
        f"Events with market reaction: "
        f"{available}"
    )

    if len(reaction_df) > 0:

        print(
            "Coverage: "
            f"{available / len(reaction_df) * 100:.2f}%"
        )

    print(
        "\nCreated files:"
    )

    print(
        " - earnings_market_reaction_v3.csv"
    )

    print(
        " - earnings_market_reaction_summary_v3.csv"
    )

    print(
        " - earnings_reaction_by_eps_class_v3.csv"
    )

    print(
        " - earnings_reaction_by_sector_v3.csv"
    )

    print(
        "\nCORPORATE EARNINGS INTELLIGENCE V3 COMPLETED"
    )


if __name__ == "__main__":
    main()
